### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by pleerock** [typestack/routing-controllers#164]
Lets discuss what we want to finish on 1.0.0 release:

- [ ] create site
- [ ] rename library?
- [ ] add cli for automatic project setup, generate controllers, middlewares, etc. 
- [ ] ...

**Comment by idchlife** [comment]
About renaming library. I don't really know if this could be a decent decision. I think naming "routing-controllers" has it's charming way of showing "not kast, lester, jester, shitux" but routing-controllers. It sticking, eventually.

**Comment by NoNameProvided** [comment]
While I see your point, I think your opinion is part of the minority. I mean no harm, I respect your opinion but we try to aim for the biggest audience. So I still think renaming is necessary.

**Comment by asaieed** [comment]
+1 with renaming the library

**Comment by idchlife** [comment]
@NoNameProvided about for bigger audience. I think there is bigger problem than the name "routing-controllers".

I guess @pleerock started to work with some kind of framework that will have ability to attach everything to it (r-controllers, s-controllers, typeorm, typedi etc). I can be wrong.

The problem (as I see) with routing-controllers that it's not fully available to work with like a full-stack framework (you still need project structure, still need to know how to config it with auth, views etc - yes you can say - learn express/koa, but if you're new and part of majority you won't be fascinated by need to fully learn express and koa to use it), but when you couple it with typedi, typeorm and your own middleware it becomes very powerful. Yes, not everyone need to work with it with orm and DI, but that's the problem with bigger audience. If you have many parts - you will not have many stars for "not so popular" libraries. There is KOA, it has stars.

Because: in terms of TypeScript and backend - not much people know about it. Not much people even use it.

I think there should be bigger project for all parts. As I mentioned somewhere here about it: I think there is need for centralized hub or something. Like Spring framework for Java or Symfony components or something. Yes, websites for each part still can exist, but some kind of centralized website will be nice.

Overall, my points:

- if renaming - routing-controllers may be formed into full framework with cookbook and other parts as "components"
- if not renaming - it can be part of something bigger. Like framework that will have structure, that will have the main NAME for it and routing-controllers will be left with it's part name.

Because well, it's just for express/koa TS simplified routing. No logic here, not much templating here, not much DB here. If you're not a pro in "structurless" project configuration - you will have a bad time. But there is start - documentation nicely provides info how to connect R-C with typedi and typeorm.

**Comment by NoNameProvided** [comment]
> I guess @pleerock started to work with some kind of framework that will have ability to attach everything to it (r-controllers, s-controllers, typeorm, typedi etc). I can be wrong.

I dont know much, but I think this is the goal of [TypeStack](https://github.com/typestack/typestack).

> The problem (as I see) with routing-controllers that it's not fully available to work with like a full-stack framework (...) If you have many parts - you will not have many stars for "not so popular" libraries.

As far as I know @pleerock thinks Typestack as a cli to scaffold project quickly with these tools.

I totally agree with you, I think the best way to make TypeStack a small abstraction over Express (even dropping support for Koa if needed) with the help of`routing-controllers`, `class-validator`, `class-converter`, `typeorm`, etc as building blocks. (So eg routing-controllers should still work with koa, but not in Typestack) will still be.

> In terms of TypeScript and backend - not much people know about it. Not much people even use it.

We are here to change that ;) Just told about routing-controllers and TypeStack at a company I have held trainings. The backend devs where blown away. So the idea is awesome we just needs to spread it, but see details in #162.

> As I mentioned somewhere here about it: I think there is need for centralized hub or something. Like Spring framework for Java or Symfony components or something. 

Would be awesome if we would be that one. 🤓  I think we have the opportuninty to become the "de facto" way to build node backend with typescript, at least devs comming from vanillia express and koa.

**Comment by BruceHem** [comment]
@pleerock what name do u have in mind? :nerd_face:

**Comment by pleerock** [comment]
I don't have any good name, and TBH I don't think I should rename this library because right now name is consistent with all other my libs, and if I rename this one, I'll need to rethink names of others as well. But yeah I agree that its not a good name for a standalone library.

**Comment by BruceHem** [comment]
This lib is so cool, 😍 When can we expect v1?

**Comment by pleerock** [comment]
once community decide with all features that should come into `1.0.0` and they will be implemented we make a release. Current `0.7.0` version is quite stable as well.

**Comment by BruceHem** [comment]
Wow after a few days with routing controllers, this lib took my code base to a whole new level and open up a new way to approve my application, this declarative approve really awesome. thanks @pleerock for this awesome work, you should write an article about this if you haven't. still can't believe it's 326 stars.

**Comment by pleerock** [comment]
thank you, its not only my work - @19majkel94 @NoNameProvided @Diluka @idchlife and all other contributors put great effort to improve this library.

**Comment by sbacem** [comment]
[TypeStack](https://github.com/typestack/typestack) 😍  is so cool.
@pleerock, @NoNameProvided I confirm the idea of @idchlife.
I think is good idea, full-stack is more reassuring for company/developer and help to create big community quickly.
The name of "routing-controllers" i think is a good 👍 when add in [typestack ](https://github.com/typestack/typestack)😎 .
Big thanks @pleerock  and all community.

**Comment by NoNameProvided** [comment]
Closing as out of date.
