### ISSUE TITLE
question: get CurrentUser in authorizationChecker

### ISSUE THREAD

**Issue by draconisNoctis** [typestack/routing-controllers#293]
I've searched the docs and sources but it seems so, that I can't get the current user in the authorizationChecker. If I use both features and want to avoid to load the user twice, I have to write some extra code for this not so rarely use case. It would be nice, when this would work out of the box.

The current user could be provided as third parameter for the authorizationChecker function.

I could take a look and maybe send a pull request if there is any interest in this feature.

**Comment by NoNameProvided** [comment]
Why do you need the current user in authorization checker? Usually you just want to check if the provided credentials is valid or not.

**Comment by NoNameProvided** [comment]
However if you need it from whatever reason it's useful to create some LRU style cache with database awareness at the size of around ~ 50-200 entity. Because querying the same user for the sub-sequent queries is wasting of resources anyway. 

For example we use routing-controllers with TypeORM and our cache is hooked into TypeORM via it's subscriber methods. So we can create caches for every entity in our db (without relations) at the specified size what will be updated if an entity is updated in the database. So eg if the one user makes 10 request it's userinfo will be queried once from the database, and kept up to date in the cache until the other user entities push it out.

**Comment by draconisNoctis** [comment]
The @Authorized decorator can take a number of roles, which has access to this action.
In the authorizationChecker I have to check, if the current user has one of these roles.

Is this a so rarely use case?

Sure, it's not that much code to implement a workaround for this but this feels a bit dirty.

**Comment by NoNameProvided** [comment]
You should use JWT token and encode the role into it. That way you dont have to query for anything.

**Comment by NoNameProvided** [comment]
> Is this a so rarely use case?

For checking roles, it's not, as I said if you have an architecture where your access tokens are stored in the db you should build some LRU style cache. Also you can use JWT token and encode the role into it. That way you dont have to query for anything but the expired tokens.

**Comment by 19majkel94** [comment]
The easiest way is fall back to good old middleware, which would do the logic with headers and DB and put the resolved user object to the `req.user` property. So it would be easily accessible in authorizationChecker.

> You need the user, but someone else will need something else, adding specific things to a general abstraction will make it definitely dirty.
We have a working solution for this - `@CurrentUser` and other decorators. They might be adapted for `authorizationChecker` or `currentUserChecker` and for future interceptors 2.0.
