### ISSUE TITLE
how to catch 404 http error when defaultErrorHandler=false

### ISSUE THREAD

**Issue by xujif** [typestack/routing-controllers#311]
I write an custom ErrorHandle implements ExpressErrorMiddlewareInterface but cannot catch 404 error.

**Comment by 19majkel94** [comment]
Because when there's no route matching the request url, it's just go out of routing-controllers stack, which behave like a big express/koa middleware. So the express/koa final handler catch no matching route, create 404 error and the default express/koa error handler return it in response.

So you should not only write custom error middleware but also custom after middleware with low priority which would behave like a guard that all request, even when no matching route has been found, will be called.

**Comment by ibox4real** [comment]
How would i know if a route was matched or not? When i write the custom after middleware it gets always called, even if a route was matched.

**Comment by NoNameProvided** [comment]
You can put this as the last middleware: 

```ts
import { Middleware, ExpressMiddlewareInterface } from 'routing-controllers';
import { NextFunction, Request, Response } from 'express';
import * as debug from 'debug';

import { NotFoundError } from './../errors/notfound.error';

@Middleware({ type: 'after' })
export class FinalMiddleware implements ExpressMiddlewareInterface {
  private logger: debug.IDebugger = debug('reputation-bot:middleware:FinalMiddleware');

  public use(req: Request, res: Response, next?: NextFunction): void {
    this.logger('FinalMiddleware reached, ending response.');
    if(!res.headersSent) {
      // TODO: match current url against every registered one
      // because finalhandler is reached if no value is returned in the controller.
      // so we need to set 404 only if really there are no path handling this.
      // or we just have to return with null?
      res.status(404);
      res.send(new NotFoundError({ id: req.path, type: 'route' }));
    }
    res.end();
  }

}
```

```ts
// ...
middlewares: [
  CorsMiddleware,
  FinalMiddleware,
  ErrorHandlerMiddleware,
],
// ...
```

**Comment by ibox4real** [comment]
Will  try this out, res.headersSent seems to be what i was looking for to determin if a response was sent
