### ISSUE TITLE
polka support

### ISSUE THREAD

**Issue by didinele** [typestack/routing-controllers#562]
[polka](https://www.npmjs.com/package/polka) is a very fast, performant express alternative.

It's really just a native HTTP server with support for middlware, routing and sub-applications, as they describe it.

It has a very similar interface to express', so the implementation shouldn't be all that difficult.

The only drawback I can see is currently [not shipping with TS declarations](https://github.com/lukeed/polka/issues/17), but there's already various typings written that could easily be used in place.

I can probably live with express, but just thought this was a nice suggestion.

**Comment by jotamorais** [comment]
@didinele, I like the suggestion (anything that improves the performance while maintaining backwards compatibility and simplicity, is welcomed).
Would you submit a PR to get this started and pitch in and help with further suggestions and contributions?

**Comment by didinele** [comment]
Currently awfully busy but will look into it next few days 👍

**Comment by NoNameProvided** [comment]
I would much rather switch to Fastify if we are switching anywhere but for now, we should not switch anywhere. There are way more optimization possibilities in our code, switching to anything won't help performance because currently not express is the bottleneck. (Personally I never hit any perf bottleneck with RC in production anyway. Maybe you did? What actual rationale justifies this change?)

Also, I think you underestimate the cost of switching, if we decide to change that means every contribution needs to 
- get familiar with polka
- will have to spenc considerable time on fixing compatibility issues which popup
