### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by nolazybits** [typestack/routing-controllers#567]
typestack in it's generality is lacking active maintainers.
Let's use this issue to see who would be keen to help

@pleerock @jotamorais ?

**Comment by nolazybits** [comment]
🖐️

**Comment by JamesMcFall** [comment]
I've come to rely on this project over the past few months so I'm happy to contribute as well.

**Comment by jotamorais** [comment]
@nolazybits & @JamesMcFall,

I merged several PRs and published a release candidate minutes ago - Release/tag **[0.9.0-alpha.1](https://github.com/typestack/routing-controllers/releases/tag/0.9.0-alpha.1)**

Please, help with tests and feedback and if it's all good, I will release `0.9.0` next week.

About the lack of active maintainer for all the TypeStack projects, I agree and I've mentioned in another issue that I will create an issue and pin in the repository and also in the README, asking for the help of maintainers, reviewers, testers and also for the community, in general, to help with roadmap, documentation, issues triage, answering questions, etc.

I'm an active user of the projects, that's why I volunteered to help with the project maintenance, but I also have my full-time job and family, which leaves me with only a few hours per week, to contribute with this project. 

All the help we can get will be welcomed.

**Comment by nolazybits** [comment]
Looking forward to see this ticket / mention somewhere.
You already have 2 volunteers :)
