### ISSUE TITLE
CVE-2022-24434

### ISSUE THREAD

**Issue by chkp-idoma** [typestack/routing-controllers#882]
Hi, 
Please fix [CVE-2022-24434](https://github.com/advisories/GHSA-wm7h-9275-46v2)
need to make sure to update dicer  to be <= 0.3.1 
(by updating multer when possible - please follow https://github.com/expressjs/multer/issues/1095)

npm ls output: 

`-- routing-controllers@0.9.0
  `-- multer@1.4.4
    `-- busboy@0.2.14
      `-- dicer@0.2.5

**Comment by zSakuraEvilz** [comment]
Is there no released version to fix this problem?. 
This repo is dead, right? 
It's been over a year and there no one new releases.

**Comment by gokuldeep-kk** [comment]
Facing a similar issue on performing a Snyk scan - https://security.snyk.io/vuln/SNYK-JS-DICER-2311764
The package version remains to be the same as mentioned above

**Comment by eladni101** [comment]
any update?

**Comment by look4regev** [comment]
It seems we have no choice but to replace to a better maintained alternative such as https://github.com/tsedio/tsed to resolve this high severity CVE. Any other ideas?

**Comment by roi972** [comment]
@look4regev @chkp-idoma  - as fas as I understand the vulnerability occurs only if you expose a route with file upload.
Also, because this project isn't maintained, you can fork this project and update the related dependency. I tried this and the project tests pass (after making a small correction), but I didn't do any other tests (degradation)

**Comment by attilaorosz** [comment]
Should be fixed

**Comment by look4regev** [comment]
Thanks! The new release looks packed with goodies. Much appreciated.
